name: Security SAST scan

on:
  pull_request:
    branches:
      - main
      - develop
      - preprod

jobs:
  semgrep: 
    runs-on: self-hosted
    permissions:
      id-token: write
      contents: read
      security-events: write
      actions: read
    
    steps:
      - name: 🧪 List files 1
        run: ls -la

      - name: 📥 Checkout du code
        uses: actions/checkout@v4

      - name: 🧪 List files 2
        run: ls -la

      - name: 🧪 check python version
        run: python3 --version

      - name: 🐍 Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 🧪 check python version
        run: python3 --version

      - name: 📦 Install semgrep and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install semgrep
          semgrep --version
      
      - name: 🆔 Generate unique and random string for unique file naming
        run: echo "UNIQ_STR=$(head /dev/urandom | tr -dc 'a-zA-Z0-9' | head -c 30)" >> "$GITHUB_ENV"

      - name: Run semgrep for scan high vulnerabilities levels and add severity result in report
        run: |
          semgrep --config=auto . --severity=ERROR \
            --sarif --sarif-output="output-${UNIQ_STR}.json" 
      
      - name: 🔄 Count and store vuln
        run: |
          jq '.runs[0].results | length' output-${UNIQ_STR}.json > vuln_count.txt
          VULN_COUNT=$(cat ./vuln_count.txt)
          echo "Nombre de vulnérabilités détectées : $VULN_COUNT"
          echo "VULN_COUNT=$VULN_COUNT" >> $GITHUB_ENV

      - name: ✅ Vérification du résultat de l’analyse
        run: |
          if [ "${VULN_COUNT}" -gt 0 ]; then
            echo "❌ ${VULN_COUNT} vulnérabilités détectées. CI bloquée."
            exit 1
          else
            echo "✅ Aucune vulnérabilité détectée. CI validée."
          fi